export const ROUTES = {
  admin: {
    dashboard: '/admin/dashboard',
    invoices: '/admin/invoices',
    projectsList: '/admin/projects',
    projects: (id: string) => `/admin/projects/${id}`,
    contractors: '/admin/contractors',
    contractor: (id: string) => `/admin/contractors/${id}`,
    team: '/admin/team',
    accounting: '/admin/accounting',
    payments: '/admin/payments/direct',
    reports: '/admin/reports/builder',
    settings: '/admin/settings',
    settingsPayments: '/admin/settings/payments',
    settingsPermissions: '/admin/settings/permissions',
    setup: '/admin/setup',
  },
  accountant: {
    queue: '/accountant/queue',
    payments: '/accountant/payments',
    holdbacks: '/accountant/holdbacks',
    bankingChanges: '/accountant/banking-changes',
    invoice: (id: string) => `/accountant/invoices/${id}`,
    contractor: (id: string) => `/accountant/contractors/${id}`,
  },
  pm: {
    dashboard: '/pm/dashboard',
    invoices: '/pm/invoices',
    invoice: (id: string) => `/pm/invoices/${id}`,
    certificates: '/pm/certificates',
    approvals: '/pm/approvals',
    projects: '/pm/projects',
    project: (id: string) => `/pm/projects/${id}`,
    contractors: '/pm/contractors',
    contractor: (id: string) => `/pm/contractors/${id}`,
  },
  vendor: {
    portal: '/vendor/portal',
    compliance: '/vendor/compliance',
    profile: '/vendor/profile',
    onboarding: '/vendor/onboarding',
  },
  shared: {
    invoice: (id: string) => `/invoices/${id}`,
    certificate: (invoiceId: string, certId: string) => `/invoices/${invoiceId}/certificates/${certId}`,
    project: (id: string) => `/projects/${id}`,
    settings: '/settings',
    unauthorized: '/unauthorized',
  },
}
